// Static opportunity data — migrated from yna-portal/shared/data/opportunities.ts
// TODO: Replace with database queries (Neon) before launch

import type { Opportunity } from "./types";

export const opportunities: Opportunity[] = [
  {
    id: "openai-bug-bounty-2025",
    title: "OpenAI Bug Bounty Program",
    organization: "OpenAI",
    type: "Competition",
    tracks: ["IT/Coding", "General"],
    description: "Find security vulnerabilities in OpenAI's systems and earn rewards",
    requirements: {
      skills: ["Security", "Programming", "Ethical Hacking"],
      experience: "Intermediate",
    },
    dates: { applicationOpen: "2025-11-01", applicationClose: "2026-12-31" },
    benefits: { monetary: "$200 - $20,000", type: ["monetary", "recognition"] },
    applicationUrl: "https://openai.com/security/bugbounty",
    location: "Remote",
    timeCommitment: "Flexible",
    difficulty: "Advanced",
  },
  {
    id: "gates-scholarship-2026",
    title: "Gates Scholarship 2026",
    organization: "Gates Foundation",
    type: "Scholarship",
    tracks: ["General"],
    description: "Full scholarship for exceptional minority students",
    requirements: {
      age: "High school seniors",
      eligibility: ["Pell-eligible", "US citizen/permanent resident"],
      experience: "Beginner",
    },
    dates: { applicationOpen: "2025-08-01", applicationClose: "2025-09-15" },
    benefits: { monetary: "Full tuition + expenses", mentorship: true, type: ["monetary", "experience"] },
    applicationUrl: "https://www.thegatesscholarship.org",
    location: "USA",
    successRate: "0.5% acceptance",
    alumniNotes: "Start essay early, focus on leadership impact",
    difficulty: "Expert",
  },
  {
    id: "first-robotics-2026",
    title: "FIRST Robotics Competition 2026",
    organization: "FIRST",
    type: "Competition",
    tracks: ["Engineering", "IT/Coding"],
    description: "Design, build, and program robots to compete in challenges",
    requirements: {
      age: "Grades 9-12",
      skills: ["Robotics", "Programming", "CAD", "Teamwork"],
      experience: "Beginner",
    },
    dates: { applicationOpen: "2025-11-01", applicationClose: "2026-01-15", programStart: "2026-01-04", programEnd: "2026-04-30" },
    benefits: { equipment: ["Robot kit", "Tools"], experience: "Engineering & teamwork", certificate: true, type: ["equipment", "experience", "recognition"] },
    applicationUrl: "https://www.firstinspires.org",
    location: "Chicago, IL",
    timeCommitment: "15-20 hours/week",
    successRate: "High participation",
    alumniNotes: "Great for college apps, builds real engineering skills",
    difficulty: "Intermediate",
  },
  {
    id: "nasa-stem-challenge-2026",
    title: "NASA STEM Challenge",
    organization: "NASA",
    type: "Competition",
    tracks: ["Engineering", "IT/Coding"],
    description: "Solve real NASA engineering challenges",
    requirements: { age: "Grades 9-12", skills: ["Engineering", "Problem Solving", "Research"], experience: "Intermediate" },
    dates: { applicationOpen: "2025-11-01", applicationClose: "2026-01-31", programEnd: "2026-05-01" },
    benefits: { monetary: "$5,000 team prize", mentorship: true, certificate: true, type: ["monetary", "experience", "recognition"] },
    applicationUrl: "https://www.nasa.gov/stem",
    location: "Remote",
    timeCommitment: "10-15 hours total",
    successRate: "15% finalist rate",
    difficulty: "Advanced",
  },
  {
    id: "adobe-creative-jam-2026",
    title: "Adobe Creative Jam Chicago",
    organization: "Adobe",
    type: "Hackathon",
    tracks: ["Media", "IT/Coding"],
    description: "72-hour design sprint using Adobe Creative Cloud",
    requirements: { age: "13+", skills: ["Photoshop", "Illustrator", "Design"], experience: "Beginner" },
    dates: { applicationOpen: "2025-11-15", applicationClose: "2026-01-10", eventDate: "2026-02-21" },
    benefits: { monetary: "$2,500 prize", equipment: ["Adobe Creative Cloud subscription"], type: ["monetary", "equipment"] },
    applicationUrl: "https://www.adobe.com/creativejam",
    location: "Chicago, IL",
    timeCommitment: "72 hours",
    successRate: "25% podium finish",
    difficulty: "Intermediate",
  },
  {
    id: "google-code-jam-2026",
    title: "Google Code Jam to I/O for Women",
    organization: "Google",
    type: "Competition",
    tracks: ["IT/Coding"],
    description: "Algorithmic coding competition with trip to Google I/O",
    requirements: { age: "18+", skills: ["Algorithms", "Data Structures", "Programming"], experience: "Advanced", eligibility: ["Women in tech"] },
    dates: { applicationOpen: "2025-11-01", applicationClose: "2026-02-28", eventDate: "2026-05-15" },
    benefits: { experience: "Trip to Google I/O", type: ["experience", "recognition"] },
    applicationUrl: "https://codingcompetitions.withgoogle.com",
    location: "Remote qualifying, finals in Bay Area",
    timeCommitment: "Multiple rounds, 2-4 hours each",
    difficulty: "Expert",
  },
  {
    id: "mlh-hackathon-season-2026",
    title: "MLH Hackathon Season Winter 2026",
    organization: "Major League Hacking",
    type: "Hackathon",
    tracks: ["IT/Coding"],
    description: "24-48 hour coding marathons across multiple cities",
    requirements: { age: "College/High school students", skills: ["Programming", "Web Development", "APIs"], experience: "Beginner" },
    dates: { applicationOpen: "2025-11-01", programStart: "2026-01-15", programEnd: "2026-02-28" },
    benefits: { monetary: "Various prizes $500-$5,000", equipment: ["Tech swag", "API credits"], type: ["monetary", "equipment", "experience"] },
    applicationUrl: "https://mlh.io",
    location: "Chicago & Remote",
    timeCommitment: "24-48 hours per event",
    successRate: "Everyone wins something",
    alumniNotes: "Best way to build portfolio projects fast",
    difficulty: "Beginner",
  },
  {
    id: "deca-icdc-2026",
    title: "DECA International Competition",
    organization: "DECA",
    type: "Competition",
    tracks: ["Business"],
    description: "Business case competitions and entrepreneurship challenges",
    requirements: { age: "High school students", skills: ["Business", "Presentation", "Marketing"], experience: "Beginner" },
    dates: { applicationOpen: "2025-11-01", applicationClose: "2026-01-31", eventDate: "2026-04-25" },
    benefits: { monetary: "Scholarships available", certificate: true, type: ["recognition", "experience"] },
    applicationUrl: "https://www.deca.org",
    location: "Regional, then Nationals",
    timeCommitment: "Weekly meetings + competition prep",
    difficulty: "Intermediate",
  },
  {
    id: "nfte-challenge-2026",
    title: "NFTE Youth Entrepreneurship Challenge",
    organization: "Network for Teaching Entrepreneurship",
    type: "Competition",
    tracks: ["Business"],
    description: "Pitch your business idea for funding and mentorship",
    requirements: { age: "Ages 13-19", skills: ["Business Planning", "Pitching"], experience: "Beginner" },
    dates: { applicationOpen: "2025-11-01", applicationClose: "2026-02-15", eventDate: "2026-05-01" },
    benefits: { monetary: "$10,000 grand prize", mentorship: true, type: ["monetary", "experience"] },
    applicationUrl: "https://www.nfte.com",
    location: "Regional & National",
    timeCommitment: "Business plan + pitch prep",
    successRate: "Regional winners advance",
    difficulty: "Intermediate",
  },
  {
    id: "tedx-youth-speaker-2026",
    title: "TEDxYouth Speaker Application",
    organization: "TEDx",
    type: "Event",
    tracks: ["Communications"],
    description: "Share your ideas worth spreading on the TEDx stage",
    requirements: { age: "Ages 13-21", skills: ["Public Speaking", "Storytelling"], experience: "Beginner" },
    dates: { applicationOpen: "2025-12-01", applicationClose: "2026-02-01", eventDate: "2026-04-15" },
    benefits: { experience: "TED talk on your resume", type: ["recognition", "experience"] },
    applicationUrl: "https://www.ted.com/tedx/events",
    location: "Various cities",
    timeCommitment: "Talk prep + event day",
    alumniNotes: "Amazing resume builder",
    difficulty: "Intermediate",
  },
  {
    id: "journalism-fellowship-2026",
    title: "Chicago Tribune Student Journalism Fellowship",
    organization: "Chicago Tribune",
    type: "Internship",
    tracks: ["Communications", "Media"],
    description: "Work alongside professional journalists",
    requirements: { age: "Ages 16-19", skills: ["Writing", "Research", "Interviewing"], experience: "Beginner" },
    dates: { applicationOpen: "2025-11-15", applicationClose: "2026-01-31", programStart: "2026-06-01", programEnd: "2026-08-15" },
    benefits: { monetary: "$15/hour stipend", experience: "Professional bylines", mentorship: true, type: ["monetary", "experience"] },
    applicationUrl: "https://www.chicagotribune.com",
    location: "Chicago, IL",
    timeCommitment: "Summer, 20 hours/week",
    successRate: "10 fellows selected",
    difficulty: "Intermediate",
  },
  {
    id: "usda-urban-farming-grant-2026",
    title: "USDA Urban Agriculture Grant",
    organization: "USDA",
    type: "Grant",
    tracks: ["Agriculture"],
    description: "Funding for urban farming projects",
    requirements: { age: "18+", skills: ["Agriculture", "Project Management"], experience: "Beginner", eligibility: ["Community organization or individual"] },
    dates: { applicationOpen: "2025-11-01", applicationClose: "2026-01-31" },
    benefits: { monetary: "Up to $25,000", type: ["monetary"] },
    applicationUrl: "https://www.usda.gov",
    location: "Chicago metro area",
    timeCommitment: "1-year project",
    difficulty: "Advanced",
  },
  {
    id: "vertical-farming-internship-2026",
    title: "The Plant Chicago Internship",
    organization: "The Plant Chicago",
    type: "Internship",
    tracks: ["Agriculture", "Engineering"],
    description: "Work in Chicago's premier vertical farming facility",
    requirements: { age: "16+", skills: ["Agriculture", "Sustainability"], experience: "Beginner" },
    dates: { applicationOpen: "2025-12-01", applicationClose: "2026-02-15", programStart: "2026-06-01", programEnd: "2026-08-31" },
    benefits: { experience: "Hands-on farming & sustainability", certificate: true, type: ["experience"] },
    applicationUrl: "https://plantchicago.org",
    location: "Chicago, IL",
    timeCommitment: "Summer, 15-20 hours/week",
    difficulty: "Beginner",
  },
  {
    id: "coca-cola-scholars-2026",
    title: "Coca-Cola Scholars Program",
    organization: "Coca-Cola Foundation",
    type: "Scholarship",
    tracks: ["General"],
    description: "$20,000 scholarship for exceptional students",
    requirements: { age: "High school seniors", experience: "Advanced", eligibility: ["US citizen/permanent resident"] },
    dates: { applicationOpen: "2025-08-01", applicationClose: "2025-10-31" },
    benefits: { monetary: "$20,000", type: ["monetary"] },
    applicationUrl: "https://www.coca-colascholarsfoundation.org",
    location: "USA",
    successRate: "150 scholars selected nationally",
    alumniNotes: "Focus on leadership and service impact",
    difficulty: "Expert",
  },
  {
    id: "regeneron-sts-2026",
    title: "Regeneron Science Talent Search",
    organization: "Regeneron",
    type: "Competition",
    tracks: ["Engineering", "IT/Coding", "General"],
    description: "Nation's oldest and most prestigious science competition",
    requirements: { age: "High school seniors", skills: ["Research", "STEM"], experience: "Advanced" },
    dates: { applicationOpen: "2025-11-01", applicationClose: "2025-11-13", eventDate: "2026-03-10" },
    benefits: { monetary: "Up to $250,000", type: ["monetary", "recognition"] },
    applicationUrl: "https://www.societyforscience.org/regeneron-sts",
    location: "Research at school, finals in DC",
    timeCommitment: "Year-long research project",
    successRate: "1.5% finalist rate",
    alumniNotes: "Most prestigious high school science award",
    difficulty: "Expert",
  },
];
